<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers/html');
JHtml::_('bootstrap.tooltip');
JHtml::_('behavior.framework');

// Create a shortcut for params.
$params  = & $this->item->params;
$images  = json_decode($this->item->images);
$canEdit = $this->item->params->get('access-edit');
$info    = $params->get('info_block_position', 0);

$aInfo1 = ($params->get('show_publish_date') || $params->get('show_parent_category') || $params->get('show_author'));
$aInfo2 = ($params->get('show_create_date') || $params->get('show_modify_date') || $params->get('show_hits'));
$topInfo = ($aInfo1 && $info != 1) || ($aInfo2 && $info == 0);
$botInfo = ($aInfo1 && $info == 1) || ($aInfo2 && $info != 0);
$icons = $params->get('access-edit') || $params->get('show_print_icon') || $params->get('show_email_icon');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));

// update catslug if not exists - compatible with 2.5
if (empty ($this->item->catslug)) {
  $this->item->catslug = $this->item->category_alias ? ($this->item->catid.':'.$this->item->category_alias) : $this->item->catid;
}

// Get Extrafields
$extrafields = new JRegistry($this->item->attribs);

$starHotel = $extrafields->get('star-hotel');
$location = $extrafields->get('location');

?>

<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate() )) : ?>
<div class="system-unpublished">
<?php endif; ?>

	<!-- Article -->
	<article class="<?php if($params->get('show_vote')) echo 'show-vote' ;?>">
    <div class="intro-image">
      <?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>

        <?php if ($params->get('show_category')) : ?>
          <?php echo JLayoutHelper::render('joomla.content.info_block.category', array('item' => $this->item, 'params' => $params)); ?>
        <?php endif; ?>
    </div>

    <?php if ($params->get('show_title')) : ?>
      <div class="title-wrap <?php if($starHotel) echo 'has-star'; ?>">
  			<?php echo JLayoutHelper::render('joomla.content.item_title', array('item' => $this->item, 'params' => $params, 'title-tag'=>'h2')); ?>

        <?php if($starHotel):?>
          <!-- Show voting form -->
          <div class="rating-info pd-rating-info">
            <div class="rating-form no-action">
              <ul class="rating-list">
                <li class="rating-current" style="width:<?php echo ($starHotel / 5) * 100; ?>%;"></li>
                <li><span title="<?php echo JText::_('JA_1_STAR_OUT_OF_5'); ?>" class="one-star"></span></li>
                <li><span title="<?php echo JText::_('JA_2_STARS_OUT_OF_5'); ?>" class="two-stars"></span></li>
                <li><span title="<?php echo JText::_('JA_3_STARS_OUT_OF_5'); ?>" class="three-stars"></span></li>
                <li><span title="<?php echo JText::_('JA_4_STARS_OUT_OF_5'); ?>" class="four-stars"></span></li>
                <li><span title="<?php echo JText::_('JA_5_STARS_OUT_OF_5'); ?>" class="five-stars"></span></li>
              </ul>
            </div>
          </div>
          <!-- End showing -->
        <?php endif ;?>
      </div>
    <?php endif; ?>

    <div class="info-review">
      <?php if($location):?>
        <div class="info-item articles-writtenby">
          <span class="fa fa-map-marker" aria-hidden="true"></span> <?php echo $location; ?>
        </div>
      <?php endif ;?>
    </div>

    <?php if (!$params->get('show_intro')) : ?>
      <?php // Content is generated by content plugin event "onContentAfterTitle" ?>
      <?php echo $this->item->event->afterDisplayTitle; ?>
    <?php endif; ?>

    <!-- Aside -->
    <?php if ($topInfo || $icons) : ?>
    <aside class="article-aside clearfix">
      <?php if ($topInfo): ?>
      <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
      <?php endif; ?>
      
      <?php if ($icons): ?>
      <?php echo JLayoutHelper::render('joomla.content.icons', array('item' => $this->item, 'params' => $params)); ?>
      <?php endif; ?>
    </aside>  
    <?php endif; ?>
    <!-- //Aside -->

    <?php if ($params->get('show_intro')) : ?>
		<section class="article-intro clearfix">
      <?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
			<?php echo $this->item->event->beforeDisplayContent; ?>

			<?php echo $this->item->introtext; ?>
		</section>
    <?php endif; ?>

    <!-- footer -->
    <?php if ($botInfo) : ?>
    <footer class="article-footer clearfix">
      <?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
      <?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
    </footer>
    <?php endif; ?>
    <!-- //footer -->


		<?php if ($params->get('show_readmore') && $this->item->readmore) :
			if ($params->get('access-view')) :
				$link = JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language));
			else :
				$menu      = JFactory::getApplication()->getMenu();
				$active    = $menu->getActive();
				$itemId    = $active->id;
        $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
        $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)));
			endif; ?>

      <?php echo JLayoutHelper::render('joomla.content.readmore', array('item' => $this->item, 'params' => $params, 'link' => $link)); ?>
      
		<?php endif; ?>

    <!-- Show voting form -->
    <?php if ($params->get('show_vote')): ?>
    <div class="rating-detail">
      <?php
        $scoreRate = Jtext::_('TPL_NO_REVIEW');
        if($this->item->rating == 1) {
          $scoreRate = Jtext::_('TPL_RATE_1');
        } elseif ($this->item->rating == 2) {
          $scoreRate = Jtext::_('TPL_RATE_2');
        } elseif ($this->item->rating == 3) {
          $scoreRate = Jtext::_('TPL_RATE_3');
        } elseif ($this->item->rating == 4) {
          $scoreRate = Jtext::_('TPL_RATE_4');
        } elseif ($this->item->rating == 5) {
          $scoreRate = Jtext::_('TPL_RATE_5');
        }
      ?>
      <span class="score"><?php echo $this->item->rating * 2; ?></span>
      <span class="list">
        <h5><?php echo $scoreRate; ?></h5>
        <?php echo $this->item->rating_count.' '.Jtext::_('TPL_REVIEWS'); ?>  
      </span>
    </div>
    <?php endif ;?>
	</article>
	<!-- //Article -->

<?php if ($this->item->state == 0 || strtotime($this->item->publish_up) > strtotime(JFactory::getDate())
|| ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate())) : ?>
</div>
<?php endif; ?>

<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?php echo $this->item->event->afterDisplayContent; ?> 
