<?php
/**
* @package		EasySocial
* @copyright	Copyright (C) 2010 - 2019 Stack Ideas Sdn Bhd. All rights reserved.
* @license		GNU/GPL, see LICENSE.php
* EasySocial is free software. This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
* See COPYRIGHT.php for copyright notices and details.
*/
defined('_JEXEC') or die('Unauthorized Access');

class SocialCronHooksLinks
{
	public function execute(&$states)
	{
		$states[] = $this->cleanupLinks();
	}

	/**
	 * Cleanup cache generated by links
	 *
	 * @since	2.0
	 * @access	public
	 */
	public function cleanupLinks()
	{
		$config = ES::config();

		if (!$config->get('links.cache.cleanup.enabled')) {
			return JText::_('COM_EASYSOCIAL_CRONJOB_LINKS_CLEANUP_DISABLED');
		}

		$months = $config->get('links.cache.cleanup.duration', '6');

		// Currently only clear the link but keep the cache image.
		// Because it will be heavy process if those cache image already stored on the Cloud server like Amazon S3
		// We will do the re-crawl proces from the link app onPrepareStream method so it will store again for those outdated link content and image.
		$model = ES::model('Links');
		$state = $model->clearExpired($months);

		return JText::_('COM_EASYSOCIAL_CRONJOB_LINKS_CLEANUP_PROCESSED');
	}
}
