<?php
/**
 * Created by PhpStorm.
 * User: jogendra
 * Date: 21/8/15
 * Time: 1:52 PM
 */
array ( '_attributes' => array ( 'id' => 'fkkrqp',
    'status' => 'submitted_for_settlement',
    'type' => 'sale',
    'currencyIsoCode' => 'USD',
    'amount' => '10.00',
    'merchantAccountId' => 'rbsl',
    'orderId' => NULL,
    'createdAt' => array ( 'date' => '2015-08-21 08:16:09',
        'timezone_type' => 3,
        'timezone' => 'UTC',
    ),
    'updatedAt' => array ( 'date' => '2015-08-21 08:16:09',
        'timezone_type' => 3,
        'timezone' => 'UTC',
    ),
    'customer' => array ( 'id' => NULL,
        'firstName' => NULL,
        'lastName' => NULL,
        'company' => NULL,
        'email' => NULL,
        'website' => NULL,
        'phone' => NULL,
        'fax' => NULL,
    ),
    'billing' => array ( 'id' => NULL,
        'firstName' => NULL,
        'lastName' => NULL,
        'company' => NULL,
        'streetAddress' => NULL,
        'extendedAddress' => NULL,
        'locality' => NULL,
        'region' => NULL,
        'postalCode' => NULL,
        'countryName' => NULL,
        'countryCodeAlpha2' => NULL,
        'countryCodeAlpha3' => NULL,
        'countryCodeNumeric' => NULL,
    ),
    'refundId' => NULL,
    'refundIds' => array ( ),
    'refundedTransactionId' => NULL,
    'settlementBatchId' => NULL,
    'shipping' => array ( 'id' => NULL,
        'firstName' => NULL,
        'lastName' => NULL,
        'company' => NULL,
        'streetAddress' => NULL,
        'extendedAddress' => NULL,
        'locality' => NULL,
        'region' => NULL,
        'postalCode' => NULL,
        'countryName' => NULL,
        'countryCodeAlpha2' => NULL,
        'countryCodeAlpha3' => NULL,
        'countryCodeNumeric' => NULL,
    ),
    'customFields' => NULL,
    'avsErrorResponseCode' => NULL,
    'avsPostalCodeResponseCode' => 'I',
    'avsStreetAddressResponseCode' => 'I',
    'cvvResponseCode' => 'I',
    'gatewayRejectionReason' => NULL,
    'processorAuthorizationCode' => 'PL04YN',
    'processorResponseCode' => '1000',
    'processorResponseText' => 'Approved',
    'additionalProcessorResponse' => NULL,
    'voiceReferralNumber' => NULL,
    'purchaseOrderNumber' => NULL,
    'taxAmount' => NULL,
    'taxExempt' => false,
    'creditCard' => array ( 'token' => NULL,
        'bin' => '401288',
        'last4' => '1881',
        'cardType' => 'Visa',
        'expirationMonth' => '10',
        'expirationYear' => '2016',
        'customerLocation' => 'US',
        'cardholderName' => NULL,
        'imageUrl' => 'https://assets.braintreegateway.com/payment_method_logo/visa.png?environment=sandbox',
        'prepaid' => 'No',
        'healthcare' => 'Unknown',
        'debit' => 'Unknown',
        'durbinRegulated' => 'Unknown',
        'commercial' => 'Unknown',
        'payroll' => 'Unknown',
        'issuingBank' => 'Unknown',
        'countryOfIssuance' => 'USA',
        'productId' => 'Unknown',
        'uniqueNumberIdentifier' => NULL,
        'venmoSdk' => false,
    ),
    'statusHistory' => array ( 0 => array ( '_attributes' => array ( 'timestamp' => array ( 'date' => '2015-08-21 08:16:09',
        'timezone_type' => 3,
        'timezone' => 'UTC',
    ),
        'status' => 'authorized',
        'amount' => '10.00',
        'user' => 'rbsl-support',
        'transactionSource' => 'api',
    ),
    ),
        1 => array ( '_attributes' => array ( 'timestamp' => array ( 'date' => '2015-08-21 08:16:09',
            'timezone_type' => 3,
            'timezone' => 'UTC',
        ),
            'status' => 'submitted_for_settlement',
            'amount' => '10.00',
            'user' => 'rbsl-support',
            'transactionSource' => 'api',
        ),
        ),
    ),
    'planId' => NULL,
    'subscriptionId' => NULL,
    'subscription' => array ( 'billingPeriodEndDate' => NULL,
        'billingPeriodStartDate' => NULL,
    ),
    'addOns' => array ( ),
    'discounts' => array ( ),
    'descriptor' => array ( '_attributes' => array ( 'name' => NULL,
        'phone' => NULL,
        'url' => NULL,
    ),
    ),
    'recurring' => false,
    'channel' => NULL,
    'serviceFeeAmount' => NULL,
    'escrowStatus' => NULL,
    'disbursementDetails' => array ( ),
    'disputes' => array ( ),
    'paymentInstrumentType' => 'credit_card',
    'processorSettlementResponseCode' => NULL,
    'processorSettlementResponseText' => NULL,
    'threeDSecureInfo' => NULL,
    'creditCardDetails' => array ( ),
    'customerDetails' => array ( '_attributes' => array ( 'id' => NULL,
        'firstName' => NULL,
        'lastName' => NULL,
        'company' => NULL,
        'email' => NULL,
        'website' => NULL,
        'phone' => NULL,
        'fax' => NULL,
    ),
    ),
    'billingDetails' => array ( ),
    'shippingDetails' => array ( ),
    'subscriptionDetails' => array ( '_attributes' => array ( 'billingPeriodEndDate' => NULL,
        'billingPeriodStartDate' => NULL,
    ),
    ),
),
)
a
b
